### ISSUE TITLE
Fails with 500 error if pipeline or organizational folders exist

### ISSUE THREAD

**Issue by tboerger** [arnarg/jenkins_exporter#1]
Hi,

I wanted to use this exporter but it results in a 500 error, I found out that it's related to this part of the code:

```
    successJobs.set(null, _.sumBy(data.jobs, x => getJobStateNumber(x.color) == 0));
    failedJobs.set(null, _.sumBy(data.jobs, x => getJobStateNumber(x.color) == 1));
    notBuiltJobs.set(null, _.sumBy(data.jobs, x => getJobStateNumber(x.color) == 2));
    disabledJobs.set(null, _.sumBy(data.jobs, x => getJobStateNumber(x.color) == 3));
    abortedJobs.set(null, _.sumBy(data.jobs, x => getJobStateNumber(x.color) == 4));
    greyJobs.set(null, _.sumBy(data.jobs, x => getJobStateNumber(x.color) == 5));
```

This expects that every job got a collor attribute, but that is not the case for `jenkins.branch.OrganizationFolder` and also not for `org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject`. There you've got a JSON response like this:

```
     { _class: 'org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject',
       name: 'foo-pipeline',
       url: 'https://jenkins.foo.com/job/foo-pipeline/' },
     { _class: 'jenkins.branch.OrganizationFolder',
       name: 'foo-core',
       url: 'https://jenkins.foo.org/job/foo-core/' },
```

It looks like if the color attribute doesn't exist you should follow the linked URL and check also on this response the jobs.

**Comment by arnarg** [comment]
I don't use multibranch and organization folders so I will probably not find the time to fix this at this time. I welcome pull requests.
